# Generated by Django 5.1.3 on 2024-12-03 06:59

import colorfield.fields
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('title', models.CharField(help_text='30 Character', max_length=30, unique=True)),
                ('english_title', models.CharField(help_text='30 Character', max_length=30, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='general-category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'hex_color'), name='color-pallet')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='50 Character', max_length=50)),
                ('english_title', models.CharField(help_text='50 Character', max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('icon', models.ImageField(blank=True, help_text='64 × 64 px', null=True, upload_to='category')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='product_app.category')),
                ('general_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='product_app.generalcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.CharField(help_text='150 Character', max_length=150)),
                ('meta_keyword', models.CharField(help_text='150 Character', max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='255 Character', max_length=255)),
                ('english_name', models.CharField(help_text='255 Character', max_length=255)),
                ('introduction', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('specification', models.JSONField(blank=True, null=True)),
                ('base_price', models.PositiveIntegerField()),
                ('special_price', models.PositiveIntegerField(blank=True, null=True)),
                ('special_price_time', models.DateTimeField(blank=True, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('second_hand', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_app.category')),
                ('color', models.ManyToManyField(blank=True, related_name='products', to='product_app.color')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.productattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('speciality', models.JSONField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, help_text='in kilobytes')),
                ('image', models.ImageField(height_field='height', help_text='800 × 800 px', upload_to='product', width_field='width')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_app.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
