# Generated by Django 5.1.3 on 2024-12-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disable_order',
            field=models.BooleanField(default=False),
        ),
    ]
