# Generated by Django 5.1.4 on 2025-02-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_product_quantity_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='products', to='product_app.color'),
        ),
    ]
