from decouple import config

KAVENEGAR_APIKEY = config('KAVENEGAR_APIKEY')
KAVENEGAR_OTP_TEMPLATENAME = config('KAVENEGAR_OTP_TEMPLATENAME')
KAVENEGAR_VERIFYORDER_TEMPLATENAME = config('KAVENEGAR_VERIFYORDER_TEMPLATENAME')
