# Generated by Django 5.1.4 on 2025-01-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='userorder',
            name='order_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
