# Generated by Django 5.2.1 on 2025-05-14 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_remove_userorder_reference_id_userorder_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='order_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
