# Generated by Django 5.1.3 on 2024-12-03 06:59

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='60 Character', max_length=60)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'verbose_name_plural': 'About us',
            },
        ),
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='30 Character', max_length=30)),
                ('image', models.ImageField(help_text='600 × 284 px', upload_to='company-logo')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='1000 × 300 px', upload_to='logo')),
                ('address', models.CharField(blank=True, help_text='150 Character', max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('call_center', models.CharField(blank=True, max_length=11, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('phone_number2', models.CharField(blank=True, max_length=11, null=True)),
                ('telegram_id', models.CharField(blank=True, help_text='50 Character', max_length=50, null=True)),
                ('instagram_id', models.CharField(blank=True, help_text='50 Character', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LargeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, help_text='in kilobytes')),
                ('url', models.URLField(blank=True, help_text='URL address to refer to a page', null=True)),
                ('status', models.BooleanField(default=True, help_text='Display status')),
                ('image', models.ImageField(height_field='height', help_text='820 × 328 px', upload_to='large-banner', width_field='width')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SliderBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='URL address to refer to a page', null=True)),
                ('status', models.BooleanField(default=True, help_text='Display status')),
                ('image', models.ImageField(help_text='2048 × 427 px', upload_to='slider-banner')),
                ('phone_image', models.ImageField(help_text='To display in mobile size - 1780 × 890 px', upload_to='slider-banner/phone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmallBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, help_text='in kilobytes')),
                ('url', models.URLField(blank=True, help_text='URL address to refer to a page', null=True)),
                ('status', models.BooleanField(default=True, help_text='Display status')),
                ('image', models.ImageField(height_field='height', help_text='400 × 300 px', upload_to='small-banner', width_field='width')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Only PDF, PNG and JPG', upload_to='uploaded-file')),
                ('size', models.FloatField(blank=True, help_text='in kilobytes')),
                ('absolute_url', models.URLField(blank=True)),
            ],
        ),
    ]
